# Generated by Django 2.1.3 on 2019-08-07 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.RemoveField(
            model_name='image',
            name='users_like',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
