# Generated by Django 2.1.3 on 2019-08-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
